#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Triston Yoder


K = 0.5522847498

def rounded_rect(x, y, w, h, r, clockwise=True):

    r = min(r, w / 2, h / 2)
    c = r * K
    if clockwise:
        return (
            f"M{x + r:.2f} {y:.2f}"
            f"H{x + w - r:.2f}"
            f"C{x + w - r + c:.2f} {y:.2f} {x + w:.2f} {y + r - c:.2f} {x + w:.2f} {y + r:.2f}"
            f"V{y + h - r:.2f}"
            f"C{x + w:.2f} {y + h - r + c:.2f} {x + w - r + c:.2f} {y + h:.2f} {x + w - r:.2f} {y + h:.2f}"
            f"H{x + r:.2f}"
            f"C{x + r - c:.2f} {y + h:.2f} {x:.2f} {y + h - r + c:.2f} {x:.2f} {y + h - r:.2f}"
            f"V{y + r:.2f}"
            f"C{x:.2f} {y + r - c:.2f} {x + r - c:.2f} {y:.2f} {x + r:.2f} {y:.2f}"
            "Z"
        )
    return (
        f"M{x + r:.2f} {y:.2f}"
        f"C{x + r - c:.2f} {y:.2f} {x:.2f} {y + r - c:.2f} {x:.2f} {y + r:.2f}"
        f"V{y + h - r:.2f}"
        f"C{x:.2f} {y + h - r + c:.2f} {x + r - c:.2f} {y + h:.2f} {x + r:.2f} {y + h:.2f}"
        f"H{x + w - r:.2f}"
        f"C{x + w - r + c:.2f} {y + h:.2f} {x + w:.2f} {y + h - r + c:.2f} {x + w:.2f} {y + h - r:.2f}"
        f"V{y + r:.2f}"
        f"C{x + w:.2f} {y + r - c:.2f} {x + w - r + c:.2f} {y:.2f} {x + w - r:.2f} {y:.2f}"
        f"H{x + r:.2f}"
        "Z"
    )

def circle(cx, cy, r):
    c = r * K
    return (
        f"M{cx:.2f} {cy - r:.2f}"
        f"C{cx + c:.2f} {cy - r:.2f} {cx + r:.2f} {cy - c:.2f} {cx + r:.2f} {cy:.2f}"
        f"C{cx + r:.2f} {cy + c:.2f} {cx + c:.2f} {cy + r:.2f} {cx:.2f} {cy + r:.2f}"
        f"C{cx - c:.2f} {cy + r:.2f} {cx - r:.2f} {cy + c:.2f} {cx - r:.2f} {cy:.2f}"
        f"C{cx - r:.2f} {cy - c:.2f} {cx - c:.2f} {cy - r:.2f} {cx:.2f} {cy - r:.2f}"
        "Z"
    )

WEIGHTS = {
    "Ultralight": dict(w=48.0, wall=3.5,  lamp=8.0,  r=15.0),
    "Regular":    dict(w=52.0, wall=6.5,  lamp=9.5,  r=16.0),
    "Black":      dict(w=58.0, wall=11.0, lamp=11.0, r=18.0),
}
SCALES = {"S": 88.0, "M": 100.0, "L": 112.0}

def artwork(weight, scale):
    p = WEIGHTS[weight]
    k = SCALES[scale] / 100.0
    h = SCALES[scale]
    w = p["w"] * k
    wall = p["wall"] * k
    lamp = p["lamp"] * k
    r = p["r"] * k
    x0, y0 = 0.0, 100.0 - h
    d = rounded_rect(x0, y0, w, h, r)
    d += rounded_rect(x0 + wall, y0 + wall, w - 2 * wall, h - 2 * wall, max(r - wall, 1.0), clockwise=False)
    cx = x0 + w / 2
    inner_top, inner_bottom = y0 + wall, y0 + h - wall
    span = inner_bottom - inner_top
    for i in range(3):
        d += circle(cx, inner_top + span * (i + 0.5) / 3, lamp)
    return d, w

def symbol_svg():

    rows = [("S", 292.0), ("M", 924.0), ("L", 1556.0)]
    cols = [("Ultralight", 263.0), ("Regular", 1290.05), ("Black", 2317.1)]
    guides, syms = [], []
    for scale, top in rows:
        guides.append(f'<line id="Capline-{scale}" x1="263" y1="{top}" x2="3036" y2="{top}"/>')
        guides.append(f'<line id="Baseline-{scale}" x1="263" y1="{top + 100}" x2="3036" y2="{top + 100}"/>')
        for weight, left in cols:
            _, w = artwork(weight, scale)
            guides.append(f'<line id="left-margin-{weight}-{scale}" x1="{left:.2f}" y1="{top - 40}" x2="{left:.2f}" y2="{top + 140}"/>')
            guides.append(f'<line id="right-margin-{weight}-{scale}" x1="{left + w:.2f}" y1="{top - 40}" x2="{left + w:.2f}" y2="{top + 140}"/>')
    for scale, top in rows:
        for weight, left in cols:
            d, _ = artwork(weight, scale)
            syms.append(
                f'<g id="{weight}-{scale}" transform="translate({left:.2f}, {top:.2f})">'
                f'<path fill-rule="evenodd" d="{d}"/></g>'
            )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by generate-stoplight-symbol.py - edit that, not this. -->\n'
        '<svg xmlns="http://www.w3.org/2000/svg" version="1.1" viewBox="0 0 3300 2200">\n'
        ' <g id="Notes"/>\n'
        ' <g id="Guides" fill="none" stroke="black" stroke-width="0.5">\n  '
        + "\n  ".join(guides)
        + '\n </g>\n <g id="Symbols">\n  '
        + "\n  ".join(syms)
        + "\n </g>\n</svg>\n"
    )

def preview_svg():
    out = []
    x = 20
    for scale in ("S", "M", "L"):
        for weight in ("Ultralight", "Regular", "Black"):
            d, w = artwork(weight, scale)
            out.append(f'<g transform="translate({x}, 20)"><path fill-rule="evenodd" d="{d}"/></g>')
            x += w + 24
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {x} 140" width="{x}" height="140">'
        f'<rect width="{x}" height="140" fill="white"/>' + "".join(out) + "</svg>"
    )

if __name__ == "__main__":
    import sys
    from pathlib import Path

    root = Path(__file__).parent
    if "--preview" in sys.argv:
        out = root / "stoplight-symbol-preview.svg"
        out.write_text(preview_svg())
    else:
        out = root / "Sources/Shared/Resources/SharedAssets.xcassets/stoplight.symbolset/stoplight.svg"
        out.write_text(symbol_svg())
    print(f"Wrote {out}")
