#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Triston Yoder


import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
OUT_DIR = Path(__file__).resolve().parent.parent / "src/ui/logo"

SOURCE = ROOT / "stoplight-13-mark-dark.png"
IDENTIFIER = "logo_13"

TARGET_WIDTH = 140

BACKGROUND = (0, 0, 0)

def to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def emit_c_array(image: Image.Image, identifier: str) -> str:
    w, h = image.size
    pixels = image.load()

    data = bytearray()
    for y in range(h):
        for x in range(w):
            r, g, b = pixels[x, y][:3]
            value = to_rgb565(r, g, b)
            data.append(value & 0xFF)
            data.append((value >> 8) & 0xFF)

    lines = [
        "// Generated by Hardware/esp32/tools/generate_logo.py from",
        f"// {SOURCE.name} — see that script for the format.",
        f"static const uint8_t {identifier}_map[] = {{",
    ]
    for i in range(0, len(data), 16):
        lines.append("  " + ", ".join(str(byte) for byte in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {identifier} = {{")
    lines.append("  .header.cf = LV_IMG_CF_TRUE_COLOR,")
    lines.append("  .header.always_zero = 0,")
    lines.append(f"  .header.w = {w},")
    lines.append(f"  .header.h = {h},")
    lines.append(f"  .data_size = {len(data)},")
    lines.append(f"  .data = {identifier}_map,")
    lines.append("};")
    return "\n".join(lines)

def main() -> None:
    if not SOURCE.exists():
        sys.exit(f"source not found: {SOURCE}")

    source = Image.open(SOURCE).convert("RGBA")
    width, height = source.size
    target_height = round(TARGET_WIDTH * height / width)
    resized = source.resize((TARGET_WIDTH, target_height), Image.LANCZOS)

    flattened = Image.new("RGB", resized.size, BACKGROUND)
    flattened.paste(resized, mask=resized.split()[3])

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    c_path = OUT_DIR / "logo.c"
    c_path.write_text('#include "logo.h"\n\n' + emit_c_array(flattened, IDENTIFIER) + "\n")
    print(f"wrote {c_path} ({TARGET_WIDTH}x{target_height}, {TARGET_WIDTH * target_height * 2} bytes)")

    h_path = OUT_DIR / "logo.h"
    h_path.write_text(
        '// The static "13" brand mark for the pager\'s waiting-for-producer\n'
        "// screen — see generate_logo.py. LV_IMG_CF_TRUE_COLOR with the black\n"
        "// screen background already composited in, so it needs no recolor and\n"
        "// no alpha blending; draw it with lv_img_set_src() as-is.\n"
        "#pragma once\n"
        "#include <lvgl.h>\n\n"
        f'extern const lv_img_dsc_t {IDENTIFIER}; // "13" mark, {TARGET_WIDTH}x{target_height}px\n'
    )
    print(f"wrote {h_path}")

    preview = OUT_DIR / "logo-preview.png"
    flattened.save(preview)
    print(f"wrote {preview}")

if __name__ == "__main__":
    sys.exit(main())
